# Generated by Django 2.1.7 on 2019-02-14 15:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Black Panther', 'Black Panther'), ('BlacKkKlansman', 'BlacKkKlansman'), ('Bohemian Rhapsody', 'Bohemian Rhapsody'), ('The Favourite”', 'The Favourite”'), ('Green Book', 'Green Book'), ('Roma', 'Roma'), ('A Star Is Born', 'A Star Is Born'), ('Vice', 'Vice'), ('News', 'News')], max_length=50)),
                ('score', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('summary', models.TextField()),
                ('post_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
