# Generated by Django 2.1.7 on 2019-02-14 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oscars_vote', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviechoice',
            name='summary',
        ),
        migrations.AddField(
            model_name='moviechoice',
            name='choice_explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='moviechoice',
            name='title',
            field=models.CharField(choices=[('Black Panther', 'Black Panther'), ('BlacKkKlansman', 'BlacKkKlansman'), ('Bohemian Rhapsody', 'Bohemian Rhapsody'), ('The Favourite”', 'The Favourite”'), ('Green Book', 'Green Book'), ('Roma', 'Roma'), ('A Star Is Born', 'A Star Is Born'), ('Vice', 'Vice')], max_length=50),
        ),
    ]
