# Generated by Django 2.1.7 on 2019-02-14 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oscars_vote', '0002_auto_20190214_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviechoice',
            name='choice_explanation',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
